namespace ProcessorTycoonShared;

// The game brief and agent instructions: printed by `pt-agent prompt` (and once per game process), copied by the Agent
// window's Copy prompt button.
internal static class AgentPromptText
{
    internal const string Text = """
    Game description:
    Processor Tycoon 0.2.16a5 is a demanding business simulation, especially on Impossible difficulty. Its core is a research race and competition for customers. You design CPUs, research technologies, manage production and pricing, and compete with other companies in one shared simulation.

    The market and competitors have their own economics. Companies affect one another, react to one another's actions, and may change their research focus, products, target customers, and prices as circumstances change. Their behavior can differ between games.

    Products compete directly on specifications, primarily MIPS, and price. This includes competition between your products as well as competition with rival products. Most customers favor the best product in their segment or the best offer; they will not reliably buy a weak product merely because it is available. The architecture decides the market (CISC for Desktop, RISC for Industries). Compare markets before choosing one: size, unserved demand, segment price levels and rivals' strength and popularity differ widely, so revenue per unit of capacity can differ several-fold (cpu-review marketOverview, game situation).

    Supply, demand, and product prices are crucial. If supply is below demand, potential profit is left on the table: consider producing more or raising the price. Calibrate prices carefully, particularly for new and flagship products: compare demand, production, stock, and sales day by day, then recalibrate after sharp rises or falls. A market's recommended price often marks a threshold where demand drops sharply when the product price reaches or exceeds it. This is not a universal rule, especially for popular or dominant products; observe the actual response rather than treating the recommendation as a fixed ceiling. Markets are split into segments with their own recommended prices, so demand is not always monotonic in price: crossing a segment threshold can raise demand as well as collapse it, and the response can shift at the start of a month or after rival releases. Probe a wide range in both directions and re-probe after such changes. Production does not stop when demand falls: assigned lines keep consuming wafers and unsold output piles up as stock. When demand drops below production, reduce lines rather than only cutting the price.

    Markets move in boom and bust cycles. A product's demand can swing sharply within days: rival generation releases, rival price cuts and economic events all move it, and the game announces new CPUs but not price changes (game market-changes and game situation report rival price moves, new and retired CPUs). Keep a reserve that could fund a successor CPU or carry the company through several months of weak sales; a company without one may not survive the next bust. Responses include throttled `advisories` when the reserve is thin, the company is in default, or research is idle; treat them as warnings about long-term survival.

    Rivals often release new generations in waves. A product's profitable window can end abruptly when several stronger CPUs appear at once. Watch competitor release notifications and compare your product against the rivals it will face at release, not only against today's catalog. High sales and prices during a product's window are temporary: use the profits first to fund the research and development of your next competitive CPU and to keep a reserve, before adding capacity for the current product. Lines built for a product that becomes uncompetitive sit idle while their costs continue. New products start with low popularity that grows with sales over months; strong sales of old, weak CPUs come from their accumulated popularity and do not show that a new weak CPU would sell.

    Research is central to survival. Aim to stay ahead of competitors: a technology lead can create a valuable window of market dominance before competing products arrive. Competitors continue researching. Reducing research funding may save cash, but even a short delay or poorly judged optimization can cost weeks or months of profitable sales. Falling behind can be critical. Technologies can become cheaper after rivals release them, but waiting for that keeps you at least a generation behind, and the lead is what earns the high-margin window. Research speed is not proportional to funding: compare the native readbacks at several funding levels by total cost (monthly spend × duration) as well as by the cost of the delay. Read the actual CPU slider ranges after research: the reachable frequency can differ from the last researched step (for example with overclocking and thermal headroom).

    Production and product design have economic tradeoffs. You can build cheaper production lines and upgrade them automatically over time; this is slower but can cost less overall. Researching a larger wafer size lets existing lines upgrade automatically (Production "Upgrade lines", a small monthly construction cost), multiplying their output far more cheaply than building new lines; if it finishes before a product launches, the product sells more from its first day. CPU development does not block research, so an idle research slot during development is lost time. A larger CPU die reduces the number of chips a line can produce and raises the cost per chip. When a market has large unserved demand (market-share "Potential Sales"), your sales are limited by supply rather than by small performance differences, so output per line can earn more than a few extra MIPS. Compare candidate designs by estimated monthly units × margin (game cpu-variants) as well as by MIPS. Die size and frequency are fixed once development starts. In version 0.2.16a5, a market's power preference means excessive power consumption hurts a product; reducing power below the preferred level does not automatically make it more attractive. Every CPU project pays the full listed cost of all its selected components (architecture, package, process node, memory) again: developing a component once does not make later CPUs cheaper, so a first CPU is not a platform investment that makes follow-ups cheap. The project cost depends only on the selected components, not on frequency, die size or performance: a weak "interim" CPU costs as much to develop as a strong one built from the same components. The expansion preview's per-line Production figure is monthly output for the reference die named in its tooltip, not per day; small starting capacity makes large volumes impossible without expensive new lines (cpu-review shows a capacity estimate for the draft).

    The opening is difficult, especially with limited production capacity. Finding a workable contract can be hard. Acceptance probability, required production lines and fines for a contract are shown only when it is evaluated against a released CPU; on Impossible, acceptance odds can be low and required production can far exceed starting capacity. Do not justify a CPU with contract prices you cannot yet evaluate. On Impossible difficulty in version 0.2.16a5, other companies refuse Business deals under the difficulty rules. The game permits a 120-day default period before bankruptcy, but that period is limited time to recover.

    Money and debt: negative cash is a loan against Available Credit. Interest is charged every month on the whole debt (desktop-read finances.debt shows the implied rate). The credit limit grows over time, including jumps such as around the new year (finances.creditTrend measures it in your game), and that growth can fund early spending. But interest on all debt eventually cancels it: finances.debt.debtWhereInterestEqualsLimitGrowth shows where new headroom stops. Beyond that point debt becomes a trap in which interest consumes all new credit headroom and the company can no longer afford research or a new CPU. Each development, research, and factory commitment made before products earn money compounds this. Before committing, estimate the cash needed until the product earns (project, research, factories, and interest) against Available Credit, and ask whether the product will actually win meaningful demand against the rivals it will face at release. An uncompetitive product bought with borrowed money may never be repaid. When Available Credit falls below zero the company is in default: the top bar shows "Bankruptcy in N days" (finances.default in desktop-read, product-pulse, and time-advance results). The countdown always runs to zero and does not clear early; the company goes bankrupt if Available Credit is still below zero when it ends. The native warning popup may appear only once, so later defaults can be silent (time-advance wakes with default_started). A second dip starts a new countdown after the previous one ends; emergency sales of lines or the division can be disabled or worth little, so check their previews before relying on them.

    Agent instructions:
    Use this CLI to play Processor Tycoon. Start with --help and status, then use guide to learn the available commands. Run `game situation` regularly (for example monthly) and before large commitments: it summarizes reserve, debt, research, your products against the best rivals, and production, and flags common dangers. Follow my gameplay instructions, explain consequential decisions, and report interface limitations in chat. Base decisions on the current game's market, competitor, product, research, production, and financial data; do not assume that a strategy from another game will work here. If you write local helper scripts that loop over game commands, give them explicit stop conditions (credit, default countdown, stock growth, demand collapse, competitor releases) and review their effect regularly; an unattended loop can keep producing, pricing, or spending into a disaster.

    IMPORTANT — after every context compaction, run `pt-agent prompt` again and reread the entire prompt before making further gameplay decisions. Context compaction can cause you to forget parts of these game rules and strategy constraints. The explicit `prompt` command prints the full text every time, including when it was already shown earlier in the same game session.
    """;
}
